"use client";

import { Copy, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import styles from "./calculations.module.css";

type Row = Record<string, string | number | boolean | [number, string] | undefined>;
type Material = { id: number; code: string; name: string; category: string; unit: string; current_price: number; active: boolean };
type LaborRate = { id: number; code: string; name: string; unit: string; current_rate: number; active: boolean };
type WorkPackage = { id: number; code: string; name: string; category: string; base_unit: string; description?: string; active: boolean; component_count?: number; materials?: Row[]; labor?: Row[]; equipment?: Row[]; transport?: Row[]; other?: Row[] };
const n = (value: unknown) => Math.max(0, Number(value) || 0);
const relationId = (value: unknown) => Array.isArray(value) ? Number(value[0]) : Number(value);
const emptyPackage = (): WorkPackage => ({ id: 0, code: "Автоматаар", name: "", category: "", base_unit: "м²", description: "", active: true, materials: [], labor: [], equipment: [], transport: [], other: [] });

export function PackageLibrary({ packages, materials, laborRates, editing, setEditing, reload, setMessage }: { packages: WorkPackage[]; materials: Material[]; laborRates: LaborRate[]; editing: WorkPackage | null; setEditing: (value: WorkPackage | null) => void; reload: () => Promise<void>; setMessage: (value: string) => void }) {
  const [q, setQ] = useState(""); const filtered = useMemo(() => packages.filter(p => `${p.code} ${p.name} ${p.category}`.toLowerCase().includes(q.toLowerCase())), [packages, q]);
  async function open(id: number) { const data = await fetch(`/api/calculations?resource=packages&package_id=${id}`).then(r => r.json()); setEditing(data); }
  function update(key: keyof WorkPackage, value: WorkPackage[keyof WorkPackage]) { setEditing(editing ? { ...editing, [key]: value } : null); }
  function lineUpdate(kind: "materials" | "labor" | "equipment" | "transport" | "other", index: number, key: string, value: string | number | boolean) { if (!editing) return; update(kind, (editing[kind] || []).map((r, i) => i === index ? { ...r, [key]: value } : r)); }
  function add(kind: "materials" | "labor" | "equipment" | "transport" | "other") { if (!editing) return; const defaults: Record<string, Row> = { materials: { material_id: 0, norm: 1, unit: "", unit_price: 0 }, labor: { labor_rate_id: 0, norm: 1, unit: "хүн/өдөр", unit_price: 0, required: true }, equipment: { name: "", norm: 1, unit: "цаг", unit_price: 0 }, transport: { name: "", norm: 1, unit: "рейс", unit_price: 0 }, other: { name: "", description: "", norm: 1, unit: "нэгж", unit_price: 0 } }; update(kind, [...(editing[kind] || []), defaults[kind]]); }
  function remove(kind: "materials" | "labor" | "equipment" | "transport" | "other", index: number) { if (editing) update(kind, (editing[kind] || []).filter((_, i) => i !== index)); }
  async function save() { if (!editing) return; if (!editing.name.trim() || !editing.category.trim() || !editing.base_unit.trim()) { setMessage("Багцын нэр, ангилал, суурь нэгжийг бөглөнө үү."); return; } if (!(editing.materials || []).length) { setMessage("Ажлын багцад заавал материалын норм оруулна уу."); return; } if (!(editing.labor || []).length) { setMessage("Ажлын багцад заавал ажлын хөлсний тооцоо оруулна уу."); return; } if ([...(editing.materials || []), ...(editing.labor || []), ...(editing.equipment || []), ...(editing.transport || []), ...(editing.other || [])].some(r => n(r.norm) <= 0)) { setMessage("Бүх норм 0-ээс их байна."); return; } const response = await fetch("/api/calculations", { method: editing.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...editing, resource: "package" }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error || "Ажлын багц хадгалж чадсангүй."); return; } setEditing(null); setMessage("Ажлын багц хадгалагдлаа."); await reload(); }
  async function copy(id: number) { await fetch("/api/calculations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "copy_package", id }) }); await reload(); }
  async function drop(id: number) { if (!confirm("Ажлын багцыг устгах уу?")) return; await fetch(`/api/calculations?resource=package&id=${id}`, { method: "DELETE" }); await reload(); }
  if (editing) return <div className={styles.formMain}><div className={styles.card}><div className={styles.sectionTitle}><h2>{editing.id ? `${editing.code} багц засах` : "Шинэ ажлын багц"}</h2><button onClick={() => setEditing(null)}><X /> Болих</button></div><div className={styles.grid}><label>Багцын код<input value={editing.code} disabled /></label><label>Багцын нэр<input value={editing.name} onChange={e => update("name", e.target.value)} /></label><label>Ангилал<input value={editing.category} onChange={e => update("category", e.target.value)} /></label><label>Суурь нэгж<input value={editing.base_unit} onChange={e => update("base_unit", e.target.value)} /></label><label className={styles.full}>Тайлбар<textarea value={editing.description || ""} onChange={e => update("description", e.target.value)} /></label><label><input type="checkbox" checked={editing.active} onChange={e => update("active", e.target.checked)} /> Идэвхтэй</label></div></div>
    <PackageSection title="Материал" onAdd={() => add("materials")} headers={["Материал", "Нэгж", "Норм", "Лавлах үнэ", ""]}>{(editing.materials || []).map((r, i) => <tr key={i}><td><select value={relationId(r.material_id) || 0} onChange={e => { const m = materials.find(x => x.id === Number(e.target.value)); lineUpdate("materials", i, "material_id", Number(e.target.value)); if (m) { lineUpdate("materials", i, "unit", m.unit); lineUpdate("materials", i, "unit_price", m.current_price); } }}><option value="0">Материал сонгох</option>{materials.filter(m => m.active).map(m => <option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select></td><NormCells kind="materials" row={r} index={i} update={lineUpdate} remove={remove} /></tr>)}</PackageSection>
    <PackageSection title="АЖЛЫН ХӨЛС — ЗААВАЛ" onAdd={() => add("labor")} headers={["Ажлын төрөл", "Нэгж", "Норм", "Нэгж үнэлгээ", ""]}>{(editing.labor || []).map((r, i) => <tr key={i}><td><select value={relationId(r.labor_rate_id) || 0} onChange={e => { const l = laborRates.find(x => x.id === Number(e.target.value)); lineUpdate("labor", i, "labor_rate_id", Number(e.target.value)); if (l) { lineUpdate("labor", i, "unit", l.unit); lineUpdate("labor", i, "unit_price", l.current_rate); } }}><option value="0">Ажлын төрөл сонгох</option>{laborRates.filter(l => l.active).map(l => <option key={l.id} value={l.id}>{l.code} · {l.name}</option>)}</select></td><NormCells kind="labor" row={r} index={i} update={lineUpdate} remove={remove} /></tr>)}</PackageSection>
    {(["equipment", "transport", "other"] as const).map(kind => <PackageSection key={kind} title={kind === "equipment" ? "Техник" : kind === "transport" ? "Тээвэр" : "Бусад зардал"} onAdd={() => add(kind)} headers={["Нэр", "Нэгж", "Норм", "Нэгж үнэ", ""]}>{(editing[kind] || []).map((r, i) => <tr key={i}><td><input value={String(r.name || "")} onChange={e => lineUpdate(kind, i, "name", e.target.value)} /></td><NormCells kind={kind} row={r} index={i} update={lineUpdate} remove={remove} /></tr>)}</PackageSection>)}
    <div className={styles.formActions}><button onClick={() => setEditing(null)}>Болих</button><button className={styles.primary} onClick={save}>Хадгалах</button></div></div>;
  return <div className={styles.card}><div className={styles.sectionTitle}><h2>Ажлын багц <small>{packages.length} багц</small></h2><button onClick={() => setEditing(emptyPackage())}><Plus /> Шинэ ажлын багц</button></div><div className={styles.filters}><label><Search /><input value={q} onChange={e => setQ(e.target.value)} placeholder="Код, нэр, ангиллаар хайх" /></label></div><div className={`${styles.tableWrap} ${styles.mobileCards}`}><table><thead><tr><th>Код</th><th>Багцын нэр</th><th>Ангилал</th><th>Суурь нэгж</th><th>Нийт бүрэлдэхүүн</th><th>Төлөв</th><th /></tr></thead><tbody>{filtered.map(p => <tr key={p.id}><td>{p.code}</td><td><strong>{p.name}</strong></td><td>{p.category}</td><td>{p.base_unit}</td><td>{p.component_count || 0}</td><td>{p.active ? "Идэвхтэй" : "Идэвхгүй"}</td><td className={styles.actions}><button aria-label="Багц засах" onClick={() => open(p.id)}><Pencil /></button><button aria-label="Багц хуулбарлах" onClick={() => copy(p.id)}><Copy /></button><button aria-label="Багц устгах" onClick={() => drop(p.id)}><Trash2 /></button></td></tr>)}</tbody></table></div></div>;
}

function PackageSection({ title, onAdd, headers, children }: { title: string; onAdd: () => void; headers: string[]; children: React.ReactNode }) { return <div className={styles.card}><div className={styles.sectionTitle}><h2>{title}</h2><button onClick={onAdd}><Plus /> Мөр нэмэх</button></div><div className={`${styles.tableWrap} ${styles.mobileLineCards}`}><table className={styles.lineTable}><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div></div>; }
function NormCells({ kind, row, index, update, remove }: { kind: "materials" | "labor" | "equipment" | "transport" | "other"; row: Row; index: number; update: (kind: "materials" | "labor" | "equipment" | "transport" | "other", index: number, key: string, value: string | number | boolean) => void; remove: (kind: "materials" | "labor" | "equipment" | "transport" | "other", index: number) => void }) { return <><td><input value={String(row.unit || "")} onChange={e => update(kind, index, "unit", e.target.value)} /></td><td><input type="number" min="0.000001" step="any" value={n(row.norm)} onChange={e => update(kind, index, "norm", n(e.target.value))} /></td><td><input type="number" min="0" value={n(row.unit_price)} onChange={e => update(kind, index, "unit_price", n(e.target.value))} /></td><td><button aria-label="Мөр устгах" onClick={() => remove(kind, index)}><X /></button></td></>; }

export function LaborRateLibrary({ rates, history, isAdmin, reload }: { rates: LaborRate[]; history: Row[]; isAdmin: boolean; reload: () => Promise<void> }) { const [editing, setEditing] = useState<Partial<LaborRate> | null>(null); async function save() { if (!editing?.name || !editing.unit) return; await fetch("/api/calculations", { method: editing.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...editing, resource: "labor_rate" }) }); setEditing(null); await reload(); } return <div className={styles.formMain}><div className={styles.card}><div className={styles.sectionTitle}><h2>Ажлын хөлсний үнэлгээ</h2>{isAdmin && <button onClick={() => setEditing({ name: "", unit: "хүн/өдөр", current_rate: 0, active: true })}><Plus /> Үнэлгээ нэмэх</button>}</div><div className={`${styles.tableWrap} ${styles.mobileCards}`}><table><thead><tr><th>Код</th><th>Ажлын төрөл</th><th>Нэгж</th><th>Нэгж үнэлгээ</th><th>Төлөв</th><th /></tr></thead><tbody>{rates.map(r => <tr key={r.id}><td>{r.code}</td><td>{r.name}</td><td>{r.unit}</td><td>{new Intl.NumberFormat("mn-MN").format(r.current_rate)}₮</td><td>{r.active ? "Идэвхтэй" : "Идэвхгүй"}</td><td>{isAdmin && <button aria-label="Үнэлгээ засах" onClick={() => setEditing(r)}><Pencil /></button>}</td></tr>)}</tbody></table></div>{editing && <div className={styles.modal}><div><h2>Ажлын хөлсний үнэлгээ</h2><label>Ажлын төрөл<input value={editing.name || ""} onChange={e => setEditing({ ...editing, name: e.target.value })} /></label><label>Нэгж<input value={editing.unit || ""} onChange={e => setEditing({ ...editing, unit: e.target.value })} /></label><label>Нэгж үнэлгээ<input type="number" min="0" value={editing.current_rate || 0} onChange={e => setEditing({ ...editing, current_rate: n(e.target.value) })} /></label><div className={styles.formActions}><button onClick={() => setEditing(null)}>Болих</button><button className={styles.primary} onClick={save}>Хадгалах</button></div></div></div>}</div><div className={styles.card}><h2>Ажлын хөлсний үнийн түүх</h2><div className={`${styles.tableWrap} ${styles.mobileCards}`}><table><thead><tr><th>Огноо</th><th>Ажлын төрөл</th><th>Хуучин үнэ</th><th>Шинэ үнэ</th><th>Өөрчилсөн</th></tr></thead><tbody>{history.map((h, i) => <tr key={i}><td>{String(h.effective_date || "")}</td><td>{Array.isArray(h.labor_rate_id) ? h.labor_rate_id[1] : ""}</td><td>{n(h.old_rate).toLocaleString()}₮</td><td>{n(h.rate).toLocaleString()}₮</td><td>{Array.isArray(h.changed_by) ? h.changed_by[1] : ""}</td></tr>)}</tbody></table></div></div></div>; }
